= Phunkhy Beats!
:showtitle:
:page-title: phunkhy beats
:page-description: A blog dedicated to iPad centered music prodction

This blog is dedicated to music production on an iPad. While my workflows might sometimes includes a laptop, for sure the iPad is in the center and I try to do things on the iPad as much as possible. Why someone wants to limit his tooling to a mobile device with quite limited screen real estate and CPU and memory contraints? 

It all started in 2019 when I installed Garage Band on my first iPad and I was surprised how well it worked and how capable it was. The more I used it to make music the more I noticed that it lets my focus more on the music because I could neither install hundreds of synths and plugins nor using more than a few at once. I tend to rather record than to edit. Moreover I was suddenly so mobile as I do not need much more than the iPad, headphones and my Korg nanoKeys Studio Bluetooth MIDI controller to make music whereever I go.

== The Blog

The idea to start the blog came when I wanted to note down what I found out to memorize it for myself. The same thing I already did for my programming. When I discover something noteworthy why just note it for yourself? Why not share with world? So, that's the reason for this blog. I'll try to structure it with meaningful tags. To be able to easily explain a specific setup I'm using https://plantuml.com/[Plantuml] which is a diagramming tool that I learned to love for software development.

== About Me

I was a computer geek from the age of 14 back in the golden age of home computers and I very early liked electronic music like Kraftwerk or Klaus Schulze. I got my first computer in 1983 (http://oldcomputers.net/atari800.html[Atari 800]) and my first synthesizer in 1984 (http://www.vintagesynth.com/korg/770.php[Korg 770]). I never learned an instrument except Djembe drumming but in 1987 my best friend spent the money he inherited on building up a home recording studio. And I was responsible for the computer and synth equipment: http://oldcomputers.net/atari520st.html[Atari ST] running https://www.youtube.com/watch?v=rPXAVGizQSY[Cubase] (MIDI only), http://www.vintagesynth.com/kawai/kawaik1.php[Kawai K1] wavetable synth and a http://www.vintagesynth.com/roland/r8.php[Roland R8] drum machine. We spent countless days and nights in that studio creating tracks, recording musicians. Then in th early 1990s techno music came into my life and heavily influenced me. The Atari ST was soon replaced with a PC running Cubase Audio (with audio tracks) and a Turtle Beach Tropez sound card (hosting a synth capable to play sf2 soundfonts).

Then I turned more to software development and when my first child was born my time was very limited and music making was only drumming my Djembe with friends. But now the iPad brought back the fun andf I think that I started a really interesting journey.


{% for post in site.posts limit: 5 %}
<a href=".{{ post.url }}">{{ post.navtitle }}</a>
{% endfor %}


{% for category in site.categories %}
  <h3>{{ category[0] }}</h3>
  <ul>
    {% for post in category[1] %}
      <li><a href="{{ post.url }}">{{ post.title }}</a></li>
    {% endfor %}
  </ul>
{% endfor %}



{% for tag in site.tags %}
  <h3>{{ tag[0] }}</h3>
  <ul>
    {% for post in tag[1] %}
      <li><a href="{{ post.url }}">{{ post.title }}</a></li>
    {% endfor %}
  </ul>
{% endfor %}
